[2023-06-18T18:12:02.863+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mult2-dag.python-operator-test manual__2023-06-18T18:12:01.515740+00:00 [queued]>
[2023-06-18T18:12:02.872+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mult2-dag.python-operator-test manual__2023-06-18T18:12:01.515740+00:00 [queued]>
[2023-06-18T18:12:02.873+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-06-18T18:12:02.884+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): python-operator-test> on 2023-06-18 18:12:01.515740+00:00
[2023-06-18T18:12:02.891+0000] {standard_task_runner.py:57} INFO - Started process 2948 to run task
[2023-06-18T18:12:02.904+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mult2-dag', 'python-operator-test', 'manual__2023-06-18T18:12:01.515740+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/mult2.py', '--cfg-path', '/tmp/tmp53k5d3au']
[2023-06-18T18:12:02.911+0000] {standard_task_runner.py:85} INFO - Job 47: Subtask python-operator-test
[2023-06-18T18:12:16.026+0000] {cli_action_loggers.py:135} WARNING - Failed to log action (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2023-06-18T18:12:16.375+0000] {task_command.py:410} INFO - Running <TaskInstance: mult2-dag.python-operator-test manual__2023-06-18T18:12:01.515740+00:00 [running]> on host 6bba1fead03c
[2023-06-18T18:12:16.631+0000] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mult2-dag' AIRFLOW_CTX_TASK_ID='python-operator-test' AIRFLOW_CTX_EXECUTION_DATE='2023-06-18T18:12:01.515740+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-18T18:12:01.515740+00:00'
[2023-06-18T18:12:16.634+0000] {logging_mixin.py:149} INFO - Secundary Task
[2023-06-18T18:12:16.634+0000] {python.py:183} INFO - Done. Returned value was: None
[2023-06-18T18:12:16.656+0000] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=mult2-dag, task_id=python-operator-test, execution_date=20230618T181201, start_date=20230618T181202, end_date=20230618T181216
[2023-06-18T18:12:16.715+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-06-18T18:12:16.747+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
