[2023-06-15T16:12:30.271+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gcs-files-dag.execute_query_save manual__2023-06-15T16:04:55.086428+00:00 [queued]>
[2023-06-15T16:12:30.278+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gcs-files-dag.execute_query_save manual__2023-06-15T16:04:55.086428+00:00 [queued]>
[2023-06-15T16:12:30.279+0000] {taskinstance.py:1308} INFO - Starting attempt 4 of 4
[2023-06-15T16:12:30.288+0000] {taskinstance.py:1327} INFO - Executing <Task(BigQueryInsertJobOperator): execute_query_save> on 2023-06-15 16:04:55.086428+00:00
[2023-06-15T16:12:30.293+0000] {standard_task_runner.py:57} INFO - Started process 2194 to run task
[2023-06-15T16:12:30.297+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gcs-files-dag', 'execute_query_save', 'manual__2023-06-15T16:04:55.086428+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/gcp_test.py', '--cfg-path', '/tmp/tmpthhgqx6l']
[2023-06-15T16:12:30.298+0000] {standard_task_runner.py:85} INFO - Job 33: Subtask execute_query_save
[2023-06-15T16:12:30.343+0000] {task_command.py:410} INFO - Running <TaskInstance: gcs-files-dag.execute_query_save manual__2023-06-15T16:04:55.086428+00:00 [running]> on host 6f3c5cb11aa3
[2023-06-15T16:12:30.407+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gcs-files-dag' AIRFLOW_CTX_TASK_ID='execute_query_save' AIRFLOW_CTX_EXECUTION_DATE='2023-06-15T16:04:55.086428+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-06-15T16:04:55.086428+00:00'
[2023-06-15T16:12:30.420+0000] {base.py:73} INFO - Using connection ID 'google_cloud_default' for task execution.
[2023-06-15T16:12:30.422+0000] {bigquery.py:2608} INFO - Executing: {'query': {'query': "\n                CREATE OR REPLACE EXTERNAL TABLE external_data\n                    OPTIONS (\n                        format = 'PARQUET',\n                        uris = ['gs://data_lake_bus_data_bus-data-389717/year=2023/month=06/day=14/hour=19/part_3ec267d7-48f5-4e1f-a19a-57889111a3e3_19:46:00.parquet']\n                    );\n                ", 'useLegacySql': False, 'writeDisposition': 'WRITE_EMPTY', 'destinationTable': {'projectId': 'bus-data-389717', 'datasetId': 'dbt_busdata_stag', 'tableId': 'external_data'}}}'
[2023-06-15T16:12:30.468+0000] {bigquery.py:1562} INFO - Inserting job ***_gcs_files_dag_execute_query_save_2023_06_15T16_04_55_086428_00_00_07646a9c08633655e490b561c08313d7
[2023-06-15T16:12:31.262+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2659, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1499, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/query.py", line 1489, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/job/base.py", line 728, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/future/polling.py", line 137, in result
    raise self._exception
google.api_core.exceptions.BadRequest: 400 Cannot set destination table in jobs with DDL statements

Location: southamerica-east1
Job ID: airflow_gcs_files_dag_execute_query_save_2023_06_15T16_04_55_086428_00_00_07646a9c08633655e490b561c08313d7

[2023-06-15T16:12:31.274+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=gcs-files-dag, task_id=execute_query_save, execution_date=20230615T160455, start_date=20230615T161230, end_date=20230615T161231
[2023-06-15T16:12:31.282+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 33 for task execute_query_save (400 Cannot set destination table in jobs with DDL statements

Location: southamerica-east1
Job ID: airflow_gcs_files_dag_execute_query_save_2023_06_15T16_04_55_086428_00_00_07646a9c08633655e490b561c08313d7
; 2194)
[2023-06-15T16:12:31.338+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-06-15T16:12:31.355+0000] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
